name = "SearchLightSQLite"
uuid = "21a827c4-482a-11ea-3a19-4d2243a4a2c5"
authors = ["Adrian Salceanu <e@essenciary.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"

[compat]
DataFrames = "0.20"
Revise = "2"
SQLite = "0.9"
SearchLight = "0"
julia = "1"
